### ISSUE TITLE
Add date picker component

### ISSUE THREAD

**Issue by klonsian** [bricksandbraces/designsystem#110]

**Comment by klonsian** [comment]
@hendriku check mal, ob wir das auch als base nutzen könnten oder ob wir vielleicht doch lieber eine komplett eigene schreiben sollten. :D 

https://github.com/flatpickr/flatpickr

**Comment by hendriku** [comment]
Wir sollten auf jeden Fall was als base nutzen zunächst.

Ich empfehle https://react-day-picker.js.org/
