### ISSUE TITLE
Create a HTML Picture Component

### ISSUE THREAD

**Issue by klonsian** [bricksandbraces/designsystem#113]
@hendriku Hast du Erfahrung aus deinen Projekten welche Auflösungen ein Bild immer mitgeben sollte pro Breakpoint (ca.)?

**Comment by hendriku** [comment]
Der Hintergrund der Frage ist ja wie besprochen die Optimierung von Images auf verschiedenen Devices um Darstellungs und Performance zu verbessern. Ich kenne verschiedene Image Optimierungsstrategien. Allerdings sind diese nicht geeignet zur Integration/Implementierung in unser Design System. 

Es gibt https://nextjs.org/docs/api-reference/next/image für SSR und bspw. https://github.com/cyrilwanner/react-optimized-image für CSR. Das sind hochspezialisierte Toolings die ihren Job sehr gut machen und super mit unserem Design System verwendbar sind. Wir sollten die User entscheiden lassen welche Lösung für ihren Anwendungsfall passt.
