### ISSUE TITLE
Construct Layouting System including Stacks

### ISSUE THREAD

**Issue by klonsian** [bricksandbraces/designsystem#117]
e.g. https://design-system.hpe.design/components/stack

@hendriku do you think it's useful?

**Comment by hendriku** [comment]
Hmm this is not part of the actual HPE design system but rather from https://v2.grommet.io/ 

![image](https://user-images.githubusercontent.com/8998518/133564235-368d1210-fb06-418e-885e-cdc72d30e740.png)
 I think they do this with their services (especially the wysiwyg editor) in mind. For this usecase such modularization is really necessary. For us it could be a comfortable way either. 
 
 
 I'd say we adapt all those components from grommet and scan their design system for more inspiration.

**Comment by hendriku** [comment]
Scheduling back now as we have to scan other designsystems for an overview first.
