### ISSUE TITLE
Create CSS prefix variable

### ISSUE THREAD

**Issue by klonsian** [bricksandbraces/designsystem#90]
We should also have a CSS prefix variable (e.g. bb or bricks or whatever) so that our CSS classnames look like: 

`bb--datatable-container__title`

**Comment by hendriku** [comment]
![WhatsApp Image 2021-09-05 at 19 16 41](https://user-images.githubusercontent.com/8998518/132137352-894951a1-4922-4e3b-82b4-09aa2b48cfec.jpeg)
